// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvmxewngatbatkrfmqmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bXhld25nYXRiYXRrcmZtcW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDY2MjAsImV4cCI6MjA3MjAyMjYyMH0.Xq-T4QAfO1tCm56UjUnU7HuwbQbgEQ0bgE36i6XRqJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});